### ISSUE TITLE
Hide angle for trees if auto-rotation mod is enabled

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/BOB#33]
There's a bunch of mods which auto-rotate trees based on world position. If any of those mods are enabled, the `Angle` option for tree replacements should probably be hidden?

* [Tree Anarchy 2.0](https://steamcommunity.com/sharedfiles/filedetails/?id=2527486462) and it's [beta version](https://steamcommunity.com/sharedfiles/filedetails/?id=2584051448)
* [Random Tree Rotation](https://steamcommunity.com/sharedfiles/filedetails/?id=556784825)
* [Tree Movement Control](https://steamcommunity.com/sharedfiles/filedetails/?id=1388613752)
* [Random Tree Rotation Natural Disasters](https://steamcommunity.com/sharedfiles/filedetails/?id=842981708)

**Comment by algernon-A** [comment]
The more I think about this, the more I lean towards removing the rotation slider for trees altogether.

**Comment by algernon-A** [comment]
Implemented in 577963d062bf2937c2976d6309d09e4ce783f2af
