### ISSUE TITLE
Ability to add props/trees to existing buildings/networks

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/BOB#41]
Being able to add props, in particular, would be super useful for adding lights/signs to things like bridge pillars, power line pylons, tunnels, etc.

(could potentially allow some interesting opportunities with Adaptive Networks mod too; eg. I could add road sign props and have AN mod show/hide them based on TMPE settings)

**Comment by algernon-A** [comment]
Indeed - already WIP, although a little while off for release.  Networks in particular need more development.

AN integration would be a later stage, but is promising.

**Comment by algernon-A** [comment]
Implemented.
