### ISSUE TITLE
Log spam re: replacement packs

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/BOB#42]
Looks like the replacement pack feature is generating lots of log spam when it tries to find the props from each of the replacement packs, most of which I have never subscribed, for example:

```
BOB - the tree and prop replacer: couldn't find pack target prop.
Unknown prefab: 50 Speed Limit  [Serialization]
```

It's not a major issue, but would be nice if there was some way to turn it off.

**Comment by algernon-A** [comment]
The "unknown prefab" spam will remain (that's the game, not the mod), but the BOB message is removed in 791befd57bad113535adf2c77b67e8785bfefc03
