### ISSUE TITLE
Option to turn off, or diminish, vanilla network tree swap thing

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/BOB#48]
When placing trees using landscaping tools, the game is way too eager to apply the tool to the nearest network - this makes placing trees close to roads, etc., a complete PITA.

Would it be possible to get an option slider to reduce the 'hit area' of networks when placing trees? 100% = whatever vanilla is, 0% = turn off entirely. Alternatively, a keyboard shortcut to toggle the vanilla tree replacer?

I assume you're also planning to do a prop version in which case it would be useful for that too.

**Comment by algernon-A** [comment]
Are the updates in 0.9.2 and 0.9.3 meeting this requirement adquately (disable vanilla tree tool and with toggle key)?

**Comment by originalfoo** [comment]
Yes, definitely :) ❤️
